### PR TITLE
Adguard Home

### LINKED ISSUE #1862: FEATURE: Add AdGuard Home Homepage Item
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

Add a homepage Item for Adguard similar to pihole
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

### PR DESCRIPTION
**Pull request by abs3ntdev**
Adding the homepage item for AdGuard Home.

Fixes #1862 

image

### CODE REVIEW

File: api/config/default.php [hunk 1]
```diff
@@ -343,27 +343,28 @@
 	'homepageOrderjdownloader' => '18',
 	'homepageOrderunifi' => '19',
 	'homepageOrderPihole' => '20',
-	'homepageOrdertautulli' => '21',
```
Comment (causefx) [inline api/config/default.php]: please keep the default ordering and place the new at 42

Comment (abs3ntdev) [reply api/config/default.php]: fixed in newest commit
